server:
  port: 80

spring:
  aop:
    proxy-target-class: true

  #datasource
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
<<<<<<< HEAD
    username: huoyUser
    password: PW123456
=======
    username: hyjc
    password: hyjc

  data:
    mongodb:
      uri: mongodb://localhost:27017/hyjc
      #uri: mongodb://name:pass@localhost:27017/dbname
>>>>>>> 45f89a48ae22d098541fca077b08d725304bd4ab



#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Dao.xml
  typeAliasesPackage: com.htht.huoy.module

pagehelper:
  helper-dialect: oracle
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


