server:
  port: 80

spring:
  aop:
    proxy-target-class: true

  #datasource
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl

    username: hyjc
    password: hyjc

  data:
    mongodb:
      uri: mongodb://localhost:27017/hyjc
      #uri: mongodb://name:pass@localhost:27017/dbname



#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Dao.xml
  typeAliasesPackage: com.htht.huoy.module

pagehelper:
  helper-dialect: oracle
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
    com.htht.huoy.module.file.dao: debug


